### ISSUE TITLE
Duplicated stringtable entry: "STR_HATG_building_requirements_info"

### ISSUE THREAD

**Issue by regiregi22** [SilenceIsFatto/HATG#15]
When trying to use the tool Tabler to check and correct the spanish translation, it detected that duplicated string error on the file \HATG\hatg\addons\gui\stringtable.xml:

-------------------------------------------------------------------------------------------------
			<Key ID="STR_HATG_building_requirements_info">
				<Original>This controls if units can hide in buildings (under a roof).</Original>
				<English>This controls if units can hide in buildings (under a roof).</English>
				<Czech>To určuje, zda se jednotky mohou skrývat v budovách (pod střechou).</Czech>
				<French>Cela contrôle si les unités peuvent se cacher dans les bâtiments (sous un toit).</French>
				<German>Dies steuert, ob Einheiten sich in Gebäuden verstecken können (unter einem Dach).</German>
				<Italian>Questo controlla se le unità possono nascondersi negli edifici (sotto un tetto).</Italian>
				<Polish>To kontroluje, czy jednostki mogą się ukrywać w budynkach (pod dachem).</Polish>
				<Russian>Это контролирует, могут ли подразделения скрываться в зданиях (под крышей).</Russian>
				<Spanish>Esto controla si las unidades pueden esconderse en edificios (bajo un techo).</Spanish>
				<Korean>유닛이 건물 내에서 숨을 수 있는지 여부를 제어합니다 (지붕 아래).</Korean>
				<Japanese>これにより、ユニットが建物内（屋根の下）に隠れることができるかどうかが制御されます。</Japanese>
				<Chinesesimp>这控制单位是否可以在建筑物内（在屋顶下）隐藏。</Chinesesimp>
				<Chinese>這控制單位是否可以在建築物內（在屋頂下）隱藏。</Chinese>
				<Portuguese>Isso controla se as unidades podem se esconder em edifícios (sob um telhado).</Portuguese>
				<Turkish>Bu, birimlerin binalarda (çatının altında) gizlenip gizlenemeyeceğini kontrol eder.</Turkish>
			</Key>

-------------------------------------------------------------------------------------------------
			<Key ID="STR_HATG_building_requirements_info">
				<Original>This controls if units that are hidden will be revealed when a nearby unit fires and is revealed.</Original>
				<English>This controls if units that are hidden will be revealed when a nearby unit fires and is revealed.</English>
				<Czech>To určuje, zda budou skryté jednotky odhaleny, když blízká jednotka vystřelí a bude odhalena.</Czech>
				<French>Cela contrôle si les unités cachées seront révélées lorsqu'une unité voisine tire et est révélée.</French>
				<German>Dies steuert, ob versteckte Einheiten aufgedeckt werden, wenn eine nahegelegene Einheit feuert und aufgedeckt wird.</German>
				<Italian>Questo controlla se le unità nascoste verranno rivelate quando una unità vicina spara e viene rivelata.</Italian>
				<Polish>To kontroluje, czy ukryte jednostki zostaną ujawnione, gdy pobliska jednostka odda strzał i zostanie ujawniona.</Polish>
				<Russian>Это контролирует, будут ли скрытые подразделения раскрыты, когда близлежащая подразделение стреляет и раскрывается.</Russian>
				<Spanish>Esto controla si las unidades ocultas serán reveladas cuando una unidad cercana dispare y sea revelada.</Spanish>
				<Korean>숨겨진 유닛이 근처의 유닛이 발사되고 드러날 때 함께 드러나는지 여부를 제어합니다.</Korean>
				<Japanese>近くのユニットが発砲し、明らかになったときに隠されたユニットが明らかになるかどうかを制御します。</Japanese>
				<Chinesesimp>这控制隐藏单位是否会在附近单位开火并被揭示时揭露。</Chinesesimp>
				<Chinese>這控制隱藏單位是否會在附近單位開火並被揭示時揭露。</Chinese>
				<Portuguese>Isso controla se as unidades escondidas serão reveladas quando uma unidade próxima disparar e for revelada.</Portuguese>
				<Turkish>Bu, yakındaki bir birim ateş ettiğinde ve ortaya çıktığında gizli birimlerin ortaya çıkıp çıkmayacağını kontrol eder.</Turkish>
			</Key>

**Comment by UAC-MaxxLite** [comment]
thank you for bringing this to our attention. a fix has already been implemented
