### ISSUE TITLE
Hidden Box applied to players block lasers

### ISSUE THREAD

**Issue by Havoc-1** [SilenceIsFatto/HATG#22]
See image attached below. 'Hidden' shows laser behind the designator whilst 'Revealed' shows the laser behaving normally. Used Better CAS Environment for visualization. While it could be ignored for rifle-based systems, it is problematic for laser-guided munitions. 

![image](https://github.com/user-attachments/assets/cb4ff60c-8c97-43f6-ac37-5fdb5ee50722)
![image](https://github.com/user-attachments/assets/cfef61c6-c2a5-4f82-b236-819dc767ac90)

**Comment by SilenceIsFatto** [comment]
If this is due to the view geometry I don't believe it can be fixed. I imagine you can still find a good spot to set up whilst hidden and then stand once you're ready to mark

**Comment by Puotek** [comment]
Couldn't you possibly check if the player is shooting/has a laser active and when that happens disable them being hidden?
