### ISSUE TITLE
Duplicated stringtable entry: "STR_HATG_UI_Enable_Fading"

### ISSUE THREAD

**Issue by regiregi22** [SilenceIsFatto/HATG#24]
When trying to use the tool Tabler to check and correct the spanish translation, it detected that duplicated string error on the file \HATG\hatg\addons\gui\stringtable.xml:

			<Key ID="STR_HATG_UI_Enable_Fading">
				<Original>Enable UI Fading</Original>
				<English>Enable UI Fading</English>
				<Russian>Включить затухание пользовательского интерфейса</Russian>
				<German>UI-Ausblenden aktivieren</German>
				<Italian>Abilita dissolvenza dell'interfaccia utente</Italian>
				<Spanish>Habilitar desvanecimiento de la interfaz de usuario</Spanish>
				<French>Activer l'estompage de l'interface utilisateur</French>
				<Korean>UI 페이드 활성화</Korean>
				<Japanese>UIフェードを有効にする</Japanese>
				<Chinesesimp>启用UI淡出</Chinesesimp>
				<Chinese>啟用UI淡出</Chinese>
				<Polish>Włącz zanikanie interfejsu użytkownika</Polish>
				<Czech>Povolit vyblednutí uživatelského rozhraní</Czech>
				<Portuguese>Ativar desvanecimento da interface do usuário</Portuguese>
				<Turkish>UI Solmasını Etkinleştir</Turkish>

			<Key ID="STR_HATG_UI_Enable_Fading">
				<Original>Enable UI Fading</Original>
				<English>Enable UI Fading</English>
				<Russian>Включить затухание пользовательского интерфейса</Russian>
				<German>UI-Fading aktivieren</German>
				<Italian>Abilita il dissolvenza dell'interfaccia utente</Italian>
				<Spanish>Activar desvanecimiento de UI</Spanish>
				<French>Activer le fondu de l'interface utilisateur</French>
				<Korean>UI 페이드 활성화</Korean>
				<Japanese>UIフェードを有効にする</Japanese>
				<Chinesesimp>启用用户界面渐隐</Chinesesimp>
				<Chinese>啟用使用者介面漸隱</Chinese>
				<Polish>Włącz przejrzystość UI</Polish>
				<Czech>Aktivovat vyblednutí UI</Czech>
				<Portuguese>Ativar desvanecimento da UI</Portuguese>
				<Turkish>UI Solmasını Etkinleştir</Turkish>
			</Key>

**Comment by regiregi22** [comment]
@SilenceIsFatto  I still keep getting duplicated string issues after correcting those two bugs (eg. STR_HATG_UI_Enable_Fading), so it may be easier if you try to fix all of them rather than me keep opening issues with each one of them.

To translate arma addons, the app Table is run over the repo folder and it detects any issues present:
https://github.com/bux/tabler

**Comment by SilenceIsFatto** [comment]
If you're going to translate anyway, why don't you just open a pull with your translations and fixes?

**Comment by regiregi22** [comment]
Because the present bugs are duplicated strings, which means that I'd have to choose which string is the valid one, and you are the creator and the one who decides that.

**Comment by SilenceIsFatto** [comment]
I couldn't find any duplicates but changed some stuff around anyway, #27
