### ISSUE TITLE
Things to consider

### ISSUE THREAD

**Issue by SilenceIsFatto** [SilenceIsFatto/HATG#26]
Add setting to disable being hidden whilst crouch
Add a variable check to canCreateMirror that will force return true if variable is set to true
Look into alt syntax for surfaceType that was introduced in 2.18
Rename "MP Support" setting to "LAN" since it doesn't work with other players

**Comment by UAC-MaxxLite** [comment]
so bypass stance 
and 
bypass conditions?

**Comment by SilenceIsFatto** [comment]
basically
