### ISSUE TITLE
Bug/Limitation: Intereferes with addAction options

### ISSUE THREAD

**Issue by 6komodo6** [SilenceIsFatto/HATG#30]
Found that the mirror interferes with accessing certain addAction options in the scroll menu such as accessing AI's backpacks. Is there a possibility to allow it to work through the mirror or have the mod temporarily switch off when player is close to friendly AI?

Alternatively if that's not possible, allow a keyboard shortcut that disables the mod and another or the same again that enables it back on to solve that

Video:
https://streamable.com/7mrj01

**Comment by SilenceIsFatto** [comment]
I could probably add a keybind to turn it on/off
