### ISSUE TITLE
Feature Request: Allow compatability with SOG AI

### ISSUE THREAD

**Issue by 6komodo6** [SilenceIsFatto/HATG#31]
SOG AI has addAction options when the player is close to the AI such as "Come to Me" and "Copy loadout", but these are sometimes blocked by the object that the HATG spawns in front of the player.

**Comment by SilenceIsFatto** [comment]
I assume this would be completed by #30 if done?

**Comment by 6komodo6** [comment]
Yeah that can work too, also can a CBA toggle be added to have the mod auto switch off when right next to friendly AI

ty

**Comment by SilenceIsFatto** [comment]
Adding a keybind to toggle it off is the simplest solution, having it check for friendly AI would be costly
